# -*- coding: utf-8 -*-
"""Copy of guessing game (first project using python)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFTDfuX3oPgXN6A-tAe3LPWVgkOnWz6Z
"""

x="noor"
guess=input("please enter a word")
count=0
limit=2
while guess!=x and count<limit:
      guess=input("please anter a word")
      count+=1

if guess == x :
  print("you win")
else:
  print("you lose")